### ISSUE TITLE
Installation ICR

### ISSUE THREAD

**Issue by Mlondolozindlovu** [staudtlex/icr#3]
Hi,

I am trying to install ICR, in order for me to perform Krippendorff's alpha and Gwet’s AC2 using ordinal data.
When using the given procedure, and I am obtaining the following error message:

> devtools::install_github("staudtlex/icr")
Downloading GitHub repo staudtlex/icr@HEAD
Error: Failed to install 'icr' from GitHub:
  Could not find tools necessary to compile a package
Call `pkgbuild::check_build_tools(debug = TRUE)` to diagnose the problem.

> install.packages(icr)
Error: object 'icr' not found

Please assist on solving this error

**Comment by staudtlex** [comment]
Hello @Mlondolozindlovu, 

thank you for your interest in ICR. 

With regard the the installation approach using `devtools::install_github`, the error decription unfortunately does not tell what exactly went wrong. I might be able to be of more assistance if I had more information about your system (operating system, R-Version, installed compiler, whether or not your system supports OpenMP, etc).

The issue with `install.packages(icr)` is much easier to address: The command should actually be:[^1]

```R
install.packages("icr")
```

Using this command should solve your problem (please do let me know if it doesn't).

[^1]: This is an error in README.md, which I'll fix this in the next release.

**Comment by Mlondolozindlovu** [comment]
Hi,

The installation error was resolved. However, I am still getting the following error:

> krippalpha(codings, metric = nominal)
Error: object 'nominal' not found

But for my analysis, I want to use ordinal metric. Please assist in resolving this error.

**Comment by Mlondolozindlovu** [comment]
I have resolved the error, thanks
