### ISSUE TITLE
Add tests

### ISSUE THREAD

**Issue by chainsawriot** [staudtlex/icr#5]
Would you like to add some unit tests to this package? I have obtained the test data from [this paper](https://dfreelon.org/publications/2010_ReCal_Intercoder_reliability_calculation_as_a_web_service.pdf). If you like, I can provide you with a PR either with `testthat` or `tinytest`.

To give you a background, I found that the `irr` to be [inaccurate](https://github.com/gesistsa/oolong/issues/96#issuecomment-2426511613). I hope that this package can be accurate in the long run.

**Comment by staudtlex** [comment]
I’d gladly add unit tests to `icr`. If you have some, just send a PR, ideally with `tinytest`, since I’d like to keep dependencies at a minimum.

**Comment by chainsawriot** [comment]
@staudtlex Good. I will be working on it with `tinytest`.
